In [1]:
! pip install -r requirements.txt
! pip install -r /home/sojungkim2/legalmaster/LegalMaster/demo/requirements.txt

  Using cached transformers-4.29.1-py3-none-any.whl (7.1 MB)
  Using cached peft-0.3.0-py3-none-any.whl (56 kB)
  Attempting uninstall: transformers
    Found existing installation: transformers 4.31.0.dev0
    Uninstalling transformers-4.31.0.dev0:
      Successfully uninstalled transformers-4.31.0.dev0
  Attempting uninstall: peft
    Found existing installation: peft 0.4.0.dev0
    Uninstalling peft-0.4.0.dev0:
      Successfully uninstalled peft-0.4.0.dev0
  Cloning https://github.com/huggingface/peft.git to /tmp/pip-req-build-7xenlgvz
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-7xenlgvz
  Resolved https://github.com/huggingface/peft.git to commit 8af8dbd2ec9b4b8f664541e9625f898db7c7c78f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-sttr88pb
  Run

In [2]:
import argparse
import logging
import random
import pickle
import tqdm
import shortuuid
import pandas as pd
import numpy as np
import os
import bitsandbytes as bn


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
bin /home/sojungkim2/anaconda/envs/legalmaster/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/sojungkim2/anaconda/envs/legalmaster/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/sojungkim2/anaconda/envs/legalmaster/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...


/home/sojungkim2/anaconda/envs/legalmaster/lib/python3.8/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "


In [7]:
## models
import torch
import torch.nn as nn
import transformers
from transformers import LlamaForCausalLM, LlamaTokenizer
from peft import PeftModel
from utils.model import load_tokenizer_and_model, load_tokenizer_and_model_multiple

### Base 모델에 학습완료한 adapter를 merge하여 parameters 보기

##### Chat

In [6]:
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

In [7]:
base_model_path = '/home/sojungkim2/legalmaster/7Boutput'
#adapter_path = './adapter/'+['llama_legal', 'llama_chat', 'llama_legal_chat', 'llama_chat_legal'][model_id]
adapter_model_path = '/home/sojungkim2/legalmaster/LegalMaster/ChatAdapterTraining/adapter_chat_checkpoints'


In [8]:
tokenizer, model, _device = load_tokenizer_and_model(base_model_path, adapter_model_path, load_8bit=True)


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [9]:
model.state_dict()

OrderedDict([('base_model.model.model.embed_tokens.weight',
              tensor([[ 9.8884e-05, -2.3329e-04,  5.8460e-04,  ..., -3.4237e-04,
                        5.9724e-05, -1.1957e-04],
                      [ 1.5289e-02, -1.2154e-02,  1.2512e-02,  ...,  1.3092e-02,
                        7.2174e-03, -6.8045e-04],
                      [ 1.7433e-03,  1.7633e-03, -1.4465e-02,  ..., -1.1444e-02,
                       -1.2665e-02,  3.7289e-04],
                      ...,
                      [-9.0179e-03,  3.0807e-02, -1.6708e-02,  ..., -1.2680e-02,
                        1.0437e-02,  4.2343e-03],
                      [-1.1368e-02, -1.4801e-02, -3.5667e-03,  ...,  6.5308e-03,
                       -2.2263e-02, -6.1455e-03],
                      [-1.3992e-02,  1.6985e-03, -2.1469e-02,  ...,  1.3527e-02,
                        2.8290e-02, -8.9111e-03]])),
             ('base_model.model.model.layers.0.self_attn.q_proj.weight',
              tensor([[-0.0096, -0.0301,  0.0085,  

In [10]:
[t for t in model.base_model.model.model.layers[2].mlp.gate_proj.lora_B.parameters()]

[Parameter containing:
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]])]

##### Legal

In [11]:
logger_1 = logging.getLogger(__name__)
logger_1.setLevel(logging.INFO)

In [12]:
base_model_path_1 = '/home/sojungkim2/legalmaster/7Boutput'
#adapter_path_1 = './adapter/'+['llama_legal', 'llama_chat', 'llama_legal_chat', 'llama_chat_legal'][model_id]
adapter_model_path_1 = '/home/sojungkim2/legalmaster/LegalMaster/LegalAdapterTraining/checkpoints'


In [13]:
tokenizer_1, model_1, _device_1 = load_tokenizer_and_model(base_model_path_1, adapter_model_path_1, load_8bit=True)


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [15]:
model_1.state_dict()

OrderedDict([('base_model.model.model.embed_tokens.weight',
              tensor([[ 9.8884e-05, -2.3329e-04,  5.8460e-04,  ..., -3.4237e-04,
                        5.9724e-05, -1.1957e-04],
                      [ 1.5289e-02, -1.2154e-02,  1.2512e-02,  ...,  1.3092e-02,
                        7.2174e-03, -6.8045e-04],
                      [ 1.7433e-03,  1.7633e-03, -1.4465e-02,  ..., -1.1444e-02,
                       -1.2665e-02,  3.7289e-04],
                      ...,
                      [-9.0179e-03,  3.0807e-02, -1.6708e-02,  ..., -1.2680e-02,
                        1.0437e-02,  4.2343e-03],
                      [-1.1368e-02, -1.4801e-02, -3.5667e-03,  ...,  6.5308e-03,
                       -2.2263e-02, -6.1455e-03],
                      [-1.3992e-02,  1.6985e-03, -2.1469e-02,  ...,  1.3527e-02,
                        2.8290e-02, -8.9111e-03]])),
             ('base_model.model.model.layers.0.self_attn.q_proj.weight',
              tensor([[-0.0096, -0.0301,  0.0085,  

In [16]:
[t for t in model_1.base_model.model.model.layers[2].mlp.gate_proj.lora_B.parameters()]

[Parameter containing:
 tensor([[-0.0012,  0.0052, -0.0058,  ..., -0.0066,  0.0007,  0.0044],
         [ 0.0054,  0.0027, -0.0018,  ..., -0.0061, -0.0045,  0.0028],
         [ 0.0063,  0.0033, -0.0038,  ..., -0.0056, -0.0070,  0.0019],
         ...,
         [ 0.0073,  0.0066, -0.0072,  ..., -0.0065, -0.0028,  0.0069],
         [-0.0077, -0.0037,  0.0060,  ...,  0.0082, -0.0004, -0.0057],
         [-0.0040,  0.0006, -0.0028,  ..., -0.0005,  0.0083,  0.0004]])]

### Chat + Legal

In [4]:
logger_2 = logging.getLogger(__name__)
logger_2.setLevel(logging.INFO)

In [5]:
base_model_path_2 = '/home/sojungkim2/legalmaster/MergeModels/base_chat'
adapter_path_1 = '/home/sojungkim2/legalmaster/LegalMaster/ChatAdapterTraining/adapter_chat_checkpoints'
adapter_path_2 = '/home/sojungkim2/legalmaster/LegalMaster/LegalAdapterTraining/checkpoints'


In [8]:
tokenizer_2, model_2, _device_2 = load_tokenizer_and_model_multiple(base_model_path_2, adapter_path_1, adapter_path_2, load_8bit=True)


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [9]:
model_2.state_dict()

OrderedDict([('base_model.model.base_model.model.model.embed_tokens.weight',
              tensor([[ 9.8884e-05, -2.3329e-04,  5.8460e-04,  ..., -3.4237e-04,
                        5.9724e-05, -1.1957e-04],
                      [ 1.5289e-02, -1.2154e-02,  1.2512e-02,  ...,  1.3092e-02,
                        7.2174e-03, -6.8045e-04],
                      [ 1.7433e-03,  1.7633e-03, -1.4465e-02,  ..., -1.1444e-02,
                       -1.2665e-02,  3.7289e-04],
                      ...,
                      [-9.0179e-03,  3.0807e-02, -1.6708e-02,  ..., -1.2680e-02,
                        1.0437e-02,  4.2343e-03],
                      [-1.1368e-02, -1.4801e-02, -3.5667e-03,  ...,  6.5308e-03,
                       -2.2263e-02, -6.1455e-03],
                      [-1.3992e-02,  1.6985e-03, -2.1469e-02,  ...,  1.3527e-02,
                        2.8290e-02, -8.9111e-03]])),
             ('base_model.model.base_model.model.model.layers.0.self_attn.q_proj.weight',
              ten

In [12]:
[t for t in model_2.base_model.base_model.model.model.layers[2].mlp.gate_proj.lora_B.parameters()]

[Parameter containing:
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]])]

In [11]:
model_2

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): PeftModelForCausalLM(
      (base_model): LoraModel(
        (model): LlamaForCausalLM(
          (model): LlamaModel(
            (embed_tokens): Embedding(32000, 4096, padding_idx=0)
            (layers): ModuleList(
              (0-31): 32 x LlamaDecoderLayer(
                (self_attn): LlamaAttention(
                  (q_proj): Linear(
                    in_features=4096, out_features=4096, bias=False
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=4096, out_features=8, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=8, out_features=4096, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embeddin